testnet deployment
mantlenetworkio/mantle pull request #364
Opened 2022-11-30 05:39 UTC by shidaxi

2022-11-30 06:02 UTC, wukongcheng approved these changes

2022-12-01 02:39 UTC, bradyjoestar requested changes

2022-12-01 02:39 UTC, bradyjoestar commented on packages/contracts/addresses-testnet.txt
> +0x29764feFbac6011d485904511b7e5282208FAECB
change to pre address for `bittesttoken`: 0x5a94dc6cc85fda49d8e9a8b85dde8629025c42be

2022-12-01 02:54 UTC, bradyjoestar approved these changes
LGTM

2022-12-01 02:54 UTC, merged